## 5. <strong>NumPy 배열</strong>

In [128]:
# Python 패키지 설치 명령어
!pip install numpy

In [129]:
# NumPy 불러오기
import numpy as np

### <strong> 5.1 NumPy 배열 생성

In [131]:
# [+] 리스트 객체로부터 ndarray 객체 생성
my_lst = [1,2,3,4,5,6]
my_arr = np.array(my_lst)

my_arr

array([1, 2, 3, 4, 5, 6])

In [132]:
type(my_arr)

numpy.ndarray

In [133]:
# [+] 리스트/NumPy 배열 동시에 생성
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

#### 리스트 컴프리헨션 vs NumPy 배열

In [135]:
prices = [20, 40, 35, 10, 25, 56]

# [+] 리스트 컴프리헨션을 이용하여 5달러씩 가격을 일괄적으로 할인하기
new_prices = [price-5 for price in prices] #(연산이나 뭐 규칙같은거) for (꺼낼 값의 이름) in (컬렉션 개체) 라고 이해하는게 편함.

new_prices

[15, 35, 30, 5, 20, 51]

In [136]:
# [+] NumPy 배열의 연산을 통한 5달러씩 가격을 일괄적으로 할인하기
prices_arr = np.array(prices)   # 배열 생성
prices_arr -= 5 # 가격 수정  =앞에 연산자 있는거는 C에서도 봄. 그거랑 같은 표현 ㅇㅇ

prices_arr 

array([15, 35, 30,  5, 20, 51])

#### 예제: 시험 점수 처리

In [138]:
# 세 번의 시험에 대한 점수를 NumPy 배열로 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [139]:
# [+] 세 번째 시험에 2점씩 더하기
test_3_fixed = test_3 + 2 # 32번 줄의 선언 파트를 실행시키지 않으면 이 코드는 실행 되지 않음.

test_3_fixed

array([89, 87, 74, 92, 94])

In [140]:
# [+] 학생 별 전체 시험 점수 총합 계산 -> total_grade
total_grade = test_1 + test_2 + test_3_fixed

total_grade

array([260, 281, 248, 276, 272])

In [141]:
# [+] 학생 별 평균 시험 점수 계산 -> final_grade
final_grade = total_grade / 3 

final_grade

array([86.66666667, 93.66666667, 82.66666667, 92.        , 90.66666667])

In [142]:
# [+] 인덱싱: Jeremy의 두 번째 시험 점수
jeremy_test_2 = test_2[3]

jeremy_test_2

93

In [143]:
# [+] Manual과 Adwoa의 첫 번째 시험 점수
manual_adwoa_test_1 = test_1[1:3] #리스트 슬라이싱이랑 동일함.

manual_adwoa_test_1

array([94, 88])

In [144]:
# [+] 전체 학생들의 점수를 2차원 배열에 저장 -> student_scores
student_scores = np.array([test_1,test_2,test_3_fixed])

student_scores

array([[ 92,  94,  88,  91,  87],
       [ 79, 100,  86,  93,  91],
       [ 89,  87,  74,  92,  94]])

In [145]:
# [+] 2차원 배열 인덱싱: Tanya의 세 번째 시험 점수
student_scores[2,0] # c느낌으로 [2][0]으로 해도 됨. 행이 먼저 나옴. [행,열]

89

In [161]:
# [+] 2차원 배열 슬라이싱: Cody의 전체 시험 점수
student_scores[:,4] #슬라이싱이 약하다...

array([87, 91, 94])

#### 배열 원소 단위의 논리 연산

In [164]:
a = np.array([1, 20, 4, 6, 28, 88, 7, 12])

# [+] 10 이상 여부를 마스킹
mask = a >= 10 # 논리연산이므로 boolean으로 생성

mask # true 인 부분집합을 얻을 때 자주 쓰는 방식임.

array([False,  True, False, False,  True,  True, False,  True])

In [166]:
# [+] 논리 연산을 이용하여 부분집합 구하기
selected = a[a >= 10] # 배열의 원소를 저장함.

selected

array([20, 28, 88, 12])

In [168]:
# [+] 논리식 결합: 논리합
selected = a[(a > 10) | (a < 8)]

selected

array([ 1, 20,  4,  6, 28, 88,  7, 12])

In [170]:
# [+] 논리식 결합: 논리곱
selected = a[(a > 10) & (a < 30)]

selected

array([20, 28, 12])

In [172]:
# [+] 정수 배열 생성
np.arange(10) # 10 직전까지 생성. stop index 사용

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
np.arange(10, 20) # 시작값, 끝값. 시작값 ~ 끝값 - 1 까지 출력. 슬라이싱이랑 비슷. start, stop index 사용

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [176]:
np.arange(10,20,3) # start,stop,distance index

array([10, 13, 16, 19])

In [178]:
# [+] 난수 배열 생성
np.random.seed(5) # seed 선언을 해두면 동일한 모양의 난수 배열이 만들어 짐. 이 시드를 써서 랜덤 값을 뽑으면 항상 동일한 값이 나옴! 마크 맵 시드를 생각하면 됨. 다른사람이 같은 시드 쓰면 똑같은거 나옴.
arr = np.random.randint(10, size =(3,5))
# index ( stop , size() ) 여기서 10을 stop 값으로 썼는데 0 ~ 9 중에 랜덤으로 뽑는다는 소리. size (3,5)는 3x5 크기의 배열을 생성한다는 뜻. 이차원 배열임. 키워드 문자 문법 참고.

arr

array([[3, 6, 6, 0, 9],
       [8, 4, 7, 0, 0],
       [7, 1, 5, 7, 0]])

### <strong>5.2 배열 조작 연산</strong>

In [181]:
# [+] 배열 속성
print(arr.ndim)     # 차원 수
print(arr.shape)    # 형상 <- 실무에서 많이 쓴다고 함.형태가 3 x 5 배열이라 이렇게 나옴.
print(arr.size)     # 크기
print(arr.dtype)    # 데이터 타입
print(arr.itemsize) # 원소별 메모리 크기(bytes) -> 정수이기 때문에 4bytes로 나옴.
print(arr.nbytes)   # 전체 메모리 크기 -> 3 x 5 크기, 각각 정수로 4byte이기 때문에 15 x 4 = 60.

2
(3, 5)
15
int32
4
60


In [183]:
# [+] 배열 슬라이싱
arr = np.arange(10)
print(arr)

print(arr[1:3]) # 슬라이싱(start:stop) <- 1,2 인덱스에 해당하는 값
print(arr[:3]) # 시작 인덱스 생략(:stop) <- 0,1,2 인덱스
print(arr[5:]) # 종료 인덱스 생략(start:) <- 5,6,7,8,9 인덱스
print(arr[::3]) # 간격(::interval) <- 0,3,6,9 인덱스 * 0빼먹음
print(arr[3:8:2]) # 슬라이싱(start:stop:interval) <-3, 5, 7 인덱스

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[0 1 2]
[5 6 7 8 9]
[0 3 6 9]
[3 5 7]


In [185]:
# [+] 난수 배열 생성
np.random.seed(0)  # [+] 시드 설정
arr = np.random.randint(10, size=(6,8)) # [+] 난수 배열 생성

arr

array([[5, 0, 3, 3, 7, 9, 3, 5],
       [2, 4, 7, 6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7]])

In [187]:
# [+] 다차원 배열 슬라이싱
arr[1:4,4:] #위에 arr 변수 이름으로 다른게 선언되면 뽑고자 하는 속성들이 안나올 수 있음.

array([[8, 8, 1, 6],
       [5, 9, 8, 9],
       [5, 0, 2, 3]])

In [197]:
# 배열 슬라이스 = 뷰(view) -> 리스트는 슬라이싱한거 다른거에 저장하고 값을 바꾸면 원본이 안바뀌지만 배열은 바뀜. 리스트는 복사본을 하나 만드는거고 배열은 복사하지않고 참조를 해서 그 값도 바뀜.
arr_sub = arr[:2, :2] # -> arr_sub에 arr 슬라이싱한걸 저장.
print(arr_sub)        # -> arr_sub 출력

arr_sub[0, 0] = 99 # -> arr_sub 
print(arr_sub)

print(arr)

[[5 0]
 [2 4]]
[[99  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]
 [ 9  9  0  4  7  3  2  7]]


In [199]:
# 배열 복사본 생성
arr_sub = arr[:2, :2].copy()  # view로 만들어지는 배열을 리스트 복사본처럼 새로 복사본 만드는 메서드. 이러면 원본 값이 안바뀜.

arr_sub[0, 0] = 55
print(arr_sub)

print(arr)

[[55  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]
 [ 9  9  0  4  7  3  2  7]]


In [211]:
# [+] 배열 재구조화: reshape()
x = np.arange(10) # 0~9로 이루어진 배열 생성 (10,)
print(x)
print(x.shape)

x = x.reshape(2,5) # 배열을 2X5 형상으로 재구조화
print(x)
print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [226]:
# [+] 배열 재구조화: 차원 추가(np.newaxis)
arr = np.arange(1,4)
print(arr)

arr_new = arr[np.newaxis, :]
print(arr_new)
print(arr_new.shape)

arr_new = arr[ :,np.newaxis]
print(arr_new)
print(arr_new.shape)


[1 2 3]
[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
(3, 1)


In [228]:
# 배열 재구조화 개인연습...
arr = np.arange(1,4)
print(arr)

arr_new = arr[np.newaxis, 1:]
print(arr_new)
print(arr_new.shape)

arr_new = arr[ 1:,np.newaxis]
print(arr_new)
print(arr_new.shape)

[1 2 3]
[[2 3]]
(1, 2)
[[2]
 [3]]
(2, 1)


#### <strong> 배열 연결하기</strong>

In [230]:
# 세 개의 배열 생성
arr_1 = np.arange(1, 4)
arr_2 = np.arange(4, 7)
arr_3 = np.arange(7, 10)

print(arr_1, arr_2, arr_3)

[1 2 3] [4 5 6] [7 8 9]


In [236]:
# [+] 배열 연결: np.concatenate()
np.concatenate([arr_1,arr_2,arr_3]) # -> 내가 원하는 순서로 나열하면 됨. 가로방향으로 쭉 붙여짐.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [242]:
# [+] 배열 연결: 종연결 -> 세로방향으로 붙여짐. 다차원 배열로 연결됨.
arr_total = np.vstack([arr_1,arr_2,arr_3])

arr_total

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [244]:
# [+] 배열 연결: 횡연결 -> concatenate()랑 동일...?
arr_total = np.hstack([arr_1,arr_2,arr_3])

arr_total

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [246]:
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

# [+] 배열 분할 [1,2,3], [99,99], [3,2,1]
arr_1, arr_2, arr_3 = np.split(arr,[3,5])  
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]
