## <strong> 8. Pandas 객체 생성 및 조작 </strong>

```Pandas``` 라이브러리 설치

In [2]:
!pip install pandas

In [3]:
import pandas as pd
import numpy as np

In [4]:
# 헬프 문서 출력
pd?

Type:        module
String form: <module 'pandas' from 'D:\\anakonda\\Lib\\site-packages\\pandas\\__init__.py'>
File:        d:\anakonda\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from Data

In [5]:
# 라이브러리 버전 확인
pd.__version__
# 사람이 만들어 놓은게 버전이 좀 다를 수 있음. 버전 맞춰줘야 그 사람껄 끌어왔을 때 문제가 없음.

'2.0.3'

### Pandas 객체: <strong> Series </strong>

In [7]:
# [+] List 객체에서 Series 객체를 생성, dict,nparray 객체도 가능.
ser = pd.Series([0.25, 0.5, 0.75, 1.0])
ser

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [8]:
# Pandas 객체 속성: .values
vals = ser.values
print(vals)
# pandas 객체의 속성들을 nparray로 반환.
pd.Series(vals)
# arry <-> series 변환이 쉬움.

[0.25 0.5  0.75 1.  ]


0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [9]:
# Pandas 객체 속성: .index
ind = ser.index
print(ind)
print(list(ind))


RangeIndex(start=0, stop=4, step=1)
[0, 1, 2, 3]


In [10]:
# [+] 레이블 기반 인덱싱, 인덱스를 지정해 줄 수 있음.
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print(ser)
print('\n|인덱스 a|\n',ser['a'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

|인덱스 a|
 0.25


### <strong> Dictionary와 Series 객체 </strong>

In [12]:
# Dictionary 객체에서 Series 객체를 생성
population_dict = {
    'California': 38332521,   # 미국 연방주 별 인구
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}

population = pd.Series(population_dict)
population

# dict에서 series로 만들면서 dict의 key 값이 index로 들어감.

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [13]:
# [+] 레이블 기반 인덱싱: 'California'에서 'New York'까지
population['California':'New York']
# 정수기반은 stop index에서 -1한 인덱스 까지만 출력하지만,
# 레이블 기반은 stop index도 가져온다.

California    38332521
Texas         26448193
New York      19651127
dtype: int64

### Pandas 객체:<strong> DataFrame </strong>

In [15]:
# 미국 연방주 별 면적
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312,
    'Illinois': 149995
}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [16]:
# [+] 'population'과 'area' Series 객체를 포함하는 DataFrame 객체 생성
states = pd.DataFrame({'population' : population, 'area' : area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [17]:
# DataFrame 객체의 인덱스와 컬럼
print(states.index)
print(states.columns)

print(states.values)
# print(states.rows) 얜 없다.

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['population', 'area'], dtype='object')
[[38332521   423967]
 [26448193   695662]
 [19651127   141297]
 [19552860   170312]
 [12882135   149995]]


In [18]:
# [+] DataFrame으로부터 Series 객체 접근하기
print('\n|states.area 출력|\n', states['area']) # 얘가 더 쓰기 좋음.
print('\n|states.area 출력|\n', states.area)
# 만약 dataframe 이름에 공백을 넣으면 .첨자로 접근하는 경우 오류가 나지만, []로 접근하면 오류가 안남.


|states.area 출력|
 California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

|states.area 출력|
 California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


#### NumPy 배열로부터 DataFrame 객체 생성
+ 예제, 오늘의 운세: 금전운(```money_fortune```), 연애운(```love_fortune```)

In [20]:
# [+] 실수 난수로 이루어진 12X2 크기의 NumPy 배열 생성
arr = np.random.rand(12,2)
arr

array([[0.82041926, 0.80973645],
       [0.37651834, 0.22989706],
       [0.95398553, 0.98191138],
       [0.66563291, 0.25979222],
       [0.40689698, 0.53637384],
       [0.51673656, 0.77641813],
       [0.83688088, 0.96132039],
       [0.13915553, 0.01165368],
       [0.09143161, 0.36757494],
       [0.97887512, 0.25512275],
       [0.18979741, 0.47743498],
       [0.23743361, 0.80606283]])

In [21]:
# NumPy 배열로부터 DataFrame 객체 생성
df = pd.DataFrame(
    arr, 
    columns=['money_fortune', 'love_fortune'], 
    index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
)

df

money_fortune  love_fortune
Jan       0.820419      0.809736
Feb       0.376518      0.229897
Mar       0.953986      0.981911
Apr       0.665633      0.259792
May       0.406897      0.536374
Jun       0.516737      0.776418
Jul       0.836881      0.961320
Aug       0.139156      0.011654
Sep       0.091432      0.367575
Oct       0.978875      0.255123
Nov       0.189797      0.477435
Dec       0.237434      0.806063

### <strong> Series 객체 조작 </strong>

#### Dictionary 스타일 조작

In [24]:
# Series 객체 생성
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print(ser)    
print('\n|ser 객체에 key값(index값)으로 "a"를 가지고 있나요?|\n','a' in ser)   # [+] Key + in 키워드
print('\n|ser 객체에 value 값으로 "0.5"를 가지고 있나요?|\n', 0.25 in ser)  # [+] Value + in 키워드
print(ser.index)    # [+] 인덱스
print(ser.keys())   # [+] 키 집합
ser['e'] = 1.25    # [+] 값 추가
ser['a'] = 0.125    # [+] 값 수정
print(ser)

# key값이나 index나 같은걸 말하는데
# key는 dict 관점에서, index는 series 관점에서 보는 것임.
# 때문에 위에서 index를 가져오나 key를 가져오나 같은 것을 볼 수 있음.

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

|ser 객체에 key값(index값)으로 "a"를 가지고 있나요?|
 True

|ser 객체에 value 값으로 "0.5"를 가지고 있나요?|
 False
Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['a', 'b', 'c', 'd'], dtype='object')
a    0.125
b    0.500
c    0.750
d    1.000
e    1.250
dtype: float64


#### 배열 스타일 조작

In [43]:
print(ser['a':'c'])   # 슬라이싱
print(ser[(ser > 0.3) & (ser < 0.8)])   # 논리 연산
# 팬시 인덱싱
ind = ['a', 'e'] 
print(ser[ind])

a    0.125
b    0.500
c    0.750
dtype: float64
b    0.50
c    0.75
dtype: float64
a    0.125
e    1.250
dtype: float64


#### Pandas 객체 인덱싱
+ 정수 기반 인덱싱(암묵적, implicit)
+ 레이블 기반 인덱싱(명시적, explicit)

In [46]:
# 슬라이싱을 이용한 'a', 'b', 'c' 선택
print(ser[0:3])   # 정수 기반 인덱싱(암묵적)
print(ser['a':'c'])     # 레이블 기반 인덱싱

a    0.125
b    0.500
c    0.750
dtype: float64
a    0.125
b    0.500
c    0.750
dtype: float64


In [48]:
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['0', '1', '2', 'd'])
print(ser[0:2])
# index를 0,1,2로 지정하면 암묵적 인덱싱과 똑같이 작동한다.


0    0.25
1    0.50
dtype: float64


### <strong> DataFrame 객체 조작 </strong>

In [98]:
# 특정 Series 객체 접근
states['area']
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [100]:
# [+] Series 객체 추가 (밀도 = 인구 / 면적)
states['density'] = states['population'] / states['area']
states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

#### 인덱서: ```loc```, ```iloc```

In [56]:
# Series 객체 생성
ser = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
ser

1    a
3    b
5    c
dtype: object

In [94]:
# loc 인덱서
print("\n|loc 인덱서 한개만 인덱싱|\n", ser.loc[1])
print("\n|loc 인덱서 여러개 인덱싱|\n", ser.loc[1:3])


|loc 인덱서 한개만 인덱싱|
 a

|loc 인덱서 여러개 인덱싱|
 1    a
3    b
dtype: object


In [102]:
# iloc 인덱서
print(ser.iloc[1])
print(ser.iloc[1:3])

b
3    b
5    c
dtype: object


In [104]:
# DataFrame 객체 = 2차원 배열
print(states.values, '\n')        # 값들을 얻어오기 , pandas로 생성한건 index랑 value로 이뤄짐.
print(states.T, '\n')             # 전치행렬
print(states.iloc[:3, :2], '\n')  # 정수 기반 슬라이싱
print(states.loc[: 'Illinois', : 'population'])  # 레이블 기반 슬라이싱

[[3.83325210e+07 4.23967000e+05 9.04139261e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]
 [1.95528600e+07 1.70312000e+05 1.14806121e+02]
 [1.28821350e+07 1.49995000e+05 8.58837628e+01]] 

              California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01   

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297 

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135


In [106]:
# loc 인덱서에선 마스킹 + 팬시 인덱싱를 지원한다.
states.loc[states.density > 100, ['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

In [108]:
# 값 수정
states.iloc[0, 2] = 90
states

population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763